=== prokaion/Questionnaire/springmvc/src/main/resources/xsd/beans.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://de.mondry/questionnaire/beans" 
	elementFormDefault="qualified" 
	targetNamespace="http://de.mondry/questionnaire/beans">
  <xs:complexType name="questionnaire">
    <xs:sequence>
      <xs:element type="tns:question" name="question" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element type="tns:questionnaire" name="questionnaire"/>
  <xs:complexType name="question">
    <xs:sequence>
      <xs:element type="xs:string" name="questionString" minOccurs="1"/>
      <xs:element type="tns:answerlist" name="answerlist" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" use="required" name="id" />
  </xs:complexType>

	<xs:complexType name="answerlist">
		<xs:sequence>
			<xs:element type="tns:answer" name="answer" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute type="xs:boolean" use="required" name="singleChoice" />
	</xs:complexType>
      
  
  <xs:complexType name="answer">
	<xs:sequence>
		<xs:element type="xs:string" name="answerString" minOccurs="0" />
		<xs:element type="tns:question" name="question" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute type="xs:boolean" use="required" name="checked" />
	<xs:attribute type="xs:boolean" use="required" name="show" />
  </xs:complexType>
            
</xs:schema>

=== prokaion/Questionnaire/springmvc/src/main/resources/xml/nosferatu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project>
<questionnaire xmlns="http://de.mondry/questionnaire/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://de.mondry/questionnaire/beans ../xsd/beans.xsd">
	<question id="1">
		<questionString>Haben Sie Kinder?</questionString>
		<answerlist singleChoice="true">
			<answer checked="false" show="true">
				<answerString>Ja</answerString>
				<question id="1.1">
					<questionString>Wie viele Kinder haben Sie?</questionString>
					<answerlist singleChoice="true">
						<answer checked="false" show="false">
							<answerString>1</answerString>
						</answer>
						<answer checked="false" show="false">
							<answerString>2</answerString>
						</answer>
						<answer checked="false" show="false">
							<answerString>3</answerString>
						</answer>
						<answer checked="false" show="false">
							<answerString>mehr</answerString>
						</answer>
					</answerlist>
				</question>
				<question id="1.2">
					<questionString>Welche Einrichtungen besuchen Ihre Kinder (mehrere
						Antworten sind hier m√∂glich)?</questionString>
					<answerlist singleChoice="false">
						<answer checked="false" show="false">
							<answerString>Kindergarten</answerString>
						</answer>
						<answer checked="false" show="false">
							<answerString>Schule</answerString>
						</answer>
						<answer checked="false" show="false">
							<answerString>Sportverein</answerString>
						</answer>
					</answerlist>
				</question>
			</answer>
			<answer checked="false" show="false">
				<answerString>Nein</answerString>
			</answer>
		</answerlist>
	</question>
	<question id="2">
		<questionString>In welchem Stadtteil wohnen Sie?</questionString>
		<answerlist singleChoice="true">
			<answer checked="false" show="false">
				<answerString>Mitte</answerString>
			</answer>
			<answer checked="false" show="false">
				<answerString>Pankow</answerString>
			</answer>
		</answerlist>
	</question>
</questionnaire>

=== prokaion/Questionnaire/springmvc/nosferatu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project>
<questionnaire xmlns="http://de.mondry/questionnaire/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://de.mondry/questionnaire/beans src/main/resources/xsd/beans.xsd">
	<question>
		<question>Haben Sie Kinder?</question>
		<answerlist singleChoice="true">
			<answer checked="false">
				<answerString>Ja</answerString>
				<question>
					<question>Wie viele Kinder haben Sie?</question>
					<answerlist singleChoice="true">
						<answer checked="false">
							<answerString>1</answerString>
						</answer>
						<answer checked="false">
							<answerString>2</answerString>
						</answer>
						<answer checked="false">
							<answerString>3</answerString>
						</answer>
						<answer checked="false">
							<answerString>mehr</answerString>
						</answer>
					</answerlist>
				</question>
				<question>
					<question>Welche Einrichtungen besuchen Ihre Kinder (mehrere
						Antworten sind hier m√∂glich)?
					</question>
					<answerlist singleChoice="false">
						<answer checked="false">
							<answerString>Kindergarten</answerString>
						</answer>
						<answer checked="false">
							<answerString>Schule</answerString>
						</answer>
						<answer checked="false">
							<answerString>Sportverein</answerString>
						</answer>
					</answerlist>
				</question>
			</answer>
			<answer checked="false">
				<answerString>Nein</answerString>
			</answer>
		</answerlist>
	</question>
	<question>
		<question>In welchem Stadtteil wohnen Sie?</question>
		<answerlist singleChoice="true">
			<answer checked="false">
				<answerString>Mitte</answerString>
			</answer>
			<answer checked="false">
				<answerString>Pankow</answerString>
			</answer>
		</answerlist>
	</question>
</questionnaire>
